apiVersion: v1
kind: Secret
metadata:
  name: api-secret
data:
  database-url: ZWN0bzovL3Bvc3RncmVzcWw6c3VwZXJzZWN1cmVwYXNzd29yZEBhcGktZGF0YWJhc2Utc2VydmljZS9hcGktcHJvZHVjdGlvbg==
  secret-key-base: dk1VL2JoOW51NGpSbng2VzJMZDVoOG8zTmFrRXl0S0ZGNnVsc0xqcnhsNkFiTmlnQWxhS3lhZ0poNitTS0VRMQ==

