apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-database
  template:
    metadata:
      labels:
        app: api-database
    spec:
      containers:
        - name: api-database
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-database-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-database-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: api-database-secret
                  key: database